services:
  mongodb:
    image: mongo:7.0
    container_name: quickbite_mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: quickbite_rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:7.2-alpine
    container_name: quickbite_redis
    ports:
      - '6379:6379'

volumes:
  mongodb_data: